### ISSUE TITLE
Wishlist Belajar #5

### ISSUE THREAD

**Issue by zainfathoni** [zainfathoni/nixpkgs#4]
## Tasks

- [ ] Encrypt files using git-crypt
- [ ] Migrate secrets from yadm to Nix
- [ ] Multiple systems setup
  - [ ] aarch64-darwin
  - [ ] x86_64-linux
- [ ] Custom package installation
  - [ ] Volta
  - [ ] Flutter
- [ ] Use Homebrew to install packages?
  - For a better version pinning
  - To install the latest version of Git instead of using the unreliable Apple Git

## Live Streaming

https://zainf.dev/belajar-5
